TRAIN_DATA = '../data/train.csv'
TEST_DATA = '../data/test.csv'
TRAIN_PROCESSED_DATA = '../data/train_processed.csv'
TEST_PROCESSED_DATA = '../data/test_processed.csv'
MODELS_PATH = '../models/'
MODEL = 'randomforest'
